import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";
import { useEffect } from "react";

export default function Terms() {
  const [, setLocation] = useLocation();
  
  // Scroll to top when component mounts
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);
  
  const scrollToSection = () => {
    // This is a placeholder since we're not scrolling on this page
    // but keeping the interface consistent with Home
  };
  
  return (
    <div className="min-h-screen flex flex-col bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100">
      <Header onNavigate={scrollToSection} />
      
      <main className="flex-grow pt-24">
        <div className="container mx-auto px-6 py-12">
          <div className="max-w-4xl mx-auto">
            <h1 className="text-4xl font-bold text-center mb-8">
              Terms and Conditions
            </h1>
            
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-8 mb-12">
              <p className="text-gray-600 dark:text-gray-400 mb-8">
                Last Updated: March 27, 2025
              </p>
              
              <h2 className="text-2xl font-semibold mb-4">1. Agreement to Terms</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                By accessing or using Jadoo 2.0's AI study assistant, you agree to be bound by these Terms and Conditions. 
                If you disagree with any part of these terms, you may not access the service.
              </p>
              
              <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                Jadoo 2.0 is an AI-powered educational platform that helps users learn through various tools 
                including AI-assisted Q&A, document summarization, flashcard generation, quiz creation, study planning, 
                and code generation. Our service is designed for educational purposes only.
              </p>
              
              <h2 className="text-2xl font-semibold mb-4">3. User Account</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                To use certain features of our service, you may need to create an account. You are responsible for 
                maintaining the confidentiality of your account information and for all activities that occur under your account. 
                You agree to notify us immediately of any unauthorized use of your account.
              </p>
              
              <h2 className="text-2xl font-semibold mb-4">4. Free Account Access</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                Jadoo 2.0 offers a free account option with access to core educational features. The free account includes:
              </p>
              <ul className="list-disc list-inside mb-6 text-gray-700 dark:text-gray-300 space-y-2">
                <li>Limited AI Q&A interactions per day</li>
                <li>Basic document summarization</li>
                <li>Simple flashcard creation</li>
                <li>Essential quiz generation</li>
                <li>Basic study planning tools</li>
              </ul>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                Usage limitations are in place to ensure fair access for all users. We reserve the right to modify the 
                features available in the free tier at any time.
              </p>
              
              <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                The content generated by our AI is provided for your personal educational use. You retain ownership of 
                any content you upload to our platform, but grant us a license to use it to provide and improve our services.
              </p>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                Our platform, including its design, algorithms, and software, is the exclusive property of Jadoo 2.0 
                and is protected by copyright, trademark, and other intellectual property laws.
              </p>
              
              <h2 className="text-2xl font-semibold mb-4">6. User Content</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                You are solely responsible for the content you upload or create using our service. You agree not to use 
                our platform to:
              </p>
              <ul className="list-disc list-inside mb-6 text-gray-700 dark:text-gray-300 space-y-2">
                <li>Violate any laws or regulations</li>
                <li>Infringe upon the intellectual property rights of others</li>
                <li>Share harmful, offensive, or inappropriate content</li>
                <li>Attempt to generate content that promotes harmful activities</li>
              </ul>
              
              <h2 className="text-2xl font-semibold mb-4">7. Limitation of Liability</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                While we strive for accuracy, our AI-generated content is provided "as is" without guarantees of 
                completeness, accuracy, or reliability. We are not liable for any errors or omissions in content, 
                or for any actions taken in reliance on such content.
              </p>
              
              <h2 className="text-2xl font-semibold mb-4">8. Changes to Terms</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                We reserve the right to modify these Terms and Conditions at any time. We will provide notice of 
                significant changes through our platform or via email. Your continued use of our service after such 
                modifications constitutes acceptance of the updated terms.
              </p>
              
              <h2 className="text-2xl font-semibold mb-4">9. Termination</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                We reserve the right to terminate or suspend your account and access to our service for violations 
                of these Terms and Conditions or for any other reason at our sole discretion.
              </p>
              
              <h2 className="text-2xl font-semibold mb-4">10. Contact Information</h2>
              <p className="text-gray-700 dark:text-gray-300 mb-6">
                If you have any questions about these Terms and Conditions, please contact us at:
                <br />
                <a href="mailto:terms@jadoo.ai" className="text-primary hover:underline">terms@jadoo.ai</a>
              </p>
              
              <div className="flex justify-center mt-8">
                <Button onClick={() => setLocation("/")} variant="outline" className="rounded-full">
                  Back to Home
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
}