import {
  AlertCircle,
  ArrowRight,
  Award,
  Book,
  BookOpen,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Code,
  Coffee,
  Cog,
  Computer,
  Copy,
  CreditCard,
  Disc,
  Download,
  File,
  FileQuestion,
  FileText,
  Gift,
  GraduationCap,
  HelpCircle,
  Home,
  Image,
  Layers,
  Layout,
  List,
  Loader2,
  LogOut,
  Mail,
  Menu,
  MessageCircle,
  MessageSquare,
  Moon,
  Pencil,
  Plus,
  Search,
  Settings,
  Sparkles,
  Square,
  Star,
  Sun,
  Timer,
  Trash,
  User,
  Wand2,
  X,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import { forwardRef } from "react";

export const Icons = {
  logo: Book,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: Disc,
  add: Plus,
  warning: AlertCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  star: Star,
  graduation: GraduationCap,
  code: Code,
  copy: Copy,
  moon: Moon,
  sun: Sun,
  laptop: Computer,
  layout: Layout,
  list: List,
  search: Search,
  coffee: Coffee,
  wand: Wand2,
  check: Check,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  home: Home,
  fileText: FileText,
  fileQuestion: FileQuestion,
  calendar: Calendar,
  layers: Layers,
  award: Award,
  clock: Clock,
  bookOpen: BookOpen,
  book: Book,
  logout: LogOut,
  mail: Mail,
  pencil: Pencil,
  square: Square,
  sparkles: Sparkles,
  download: Download,
  gift: Gift,
  timer: Timer,
  menu: Menu,
};

export type Icon = keyof typeof Icons;

interface IconProps extends LucideProps {
  name: Icon;
}

export const Icon = forwardRef<SVGSVGElement, IconProps>(
  ({ name, ...props }, ref) => {
    const Icon = Icons[name] as LucideIcon;
    return <Icon ref={ref} {...props} />;
  }
);